### ISSUE TITLE
15-align-self: readme.md 

### ISSUE THREAD

**Issue by aame1** [CodeYourFuture/html-css-git-exercises#92]
Hi, 
Would it be possible and if you judge it useful -  to add in the readme.md that `flex-direction` is also needed to change the last class `.countries--fourth` into a column ?

The readme.md doesn't mention the possibility. :)

**Comment by NateWr** [comment]
Thanks! In 9fa3231 I have adjusted the text so that the student knows they will need to use other properties to complete the exercise. 

However, I don't want to mention the specific properties or when they need to use them. The goal of these exercises is to build up a student's knowledge step-by-step. And at times like this they need  to problem solve by drawing on what they've already learned.
